# Generated by Django 2.2.5 on 2019-09-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookstore', '0002_auto_20190919_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistName',
            fields=[
                ('username', models.CharField(help_text='Placeholder till user ID ready', max_length=20, primary_key=True, serialize=False)),
                ('wish_list_name_0', models.CharField(default='Wishlist', help_text='Enter name for wishlist', max_length=20)),
                ('wish_list_name_1', models.CharField(blank=True, help_text='Enter name for wishlist', max_length=20, null=True)),
                ('wish_list_name_2', models.CharField(blank=True, help_text='Enter name for wishlist', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistEntrie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Placeholder till user ID ready', max_length=20)),
                ('home', models.CharField(choices=[('0', 'Wishlist 0'), ('1', 'Wishlist 1'), ('2', 'Wishlist 2')], help_text='Select a list to move book to new list', max_length=1)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookstore.Book')),
            ],
        ),
    ]
