from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='bookstore-home'),
    path('books', views.books, name='bookstore-books'),
    path('booksrate1', views.booksrate1, name='bookstore-booksrate1'),
    path('booksrate2', views.booksrate2, name='bookstore-booksrate2'),
    path('booksrate3', views.booksrate3, name='bookstore-booksrate3'),
    path('booksrate4', views.booksrate4, name='bookstore-booksrate4'),
    path('booksrate5', views.booksrate5, name='bookstore-booksrate5'),
    path('Fantasy', views.Fantasy, name='Fantasy'),
    path('Horror', views.Horror, name='Horror'),
    path('Nonfiction', views.Nonfiction, name='Nonfiction'),
    path('Sciencefiction', views.Sciencefiction, name='Sciencefiction'),
    path('Thriller', views.Thriller, name='Thriller'),
    path('Satire', views.Satire, name='Satire'),
    path('Bestsellers', views.Bestsellers, name='Bestsellers'),
    path('booksabc', views.booksabc, name='bookstore-booksabc'),
    path('Fantasyabc', views.Fantasyabc, name='Fantasyabc'),
    path('Horrorabc', views.Horrorabc, name='Horrorabc'),
    path('Nonfictionabc', views.Nonfictionabc, name='Nonfictionabc'),
    path('Sciencefictionabc', views.Sciencefictionabc, name='Sciencefictionabc'),
    path('Thrillerabc', views.Thrillerabc, name='Thrillerabc'),
    path('Satireabc', views.Satireabc, name='Satireabc'),
    path('Bestsellersabc', views.Bestsellersabc, name='Bestsellersabc'),
    path('booksp', views.booksp, name='bookstore-booksp'),
    path('Fantasyp', views.Fantasyp, name='Fantasyp'),
    path('Horrorp', views.Horrorp, name='Horrorp'),
    path('Nonfictionp', views.Nonfictionp, name='Nonfictionp'),
    path('Sciencefictionp', views.Sciencefictionp, name='Sciencefictionp'),
    path('Thrillerp', views.Thrillerp, name='Thrillerp'),
    path('Satirep', views.Satirep, name='Satirep'),
    path('Bestsellersp', views.Bestsellersp, name='Bestsellersp'),
    path('booksabcp', views.booksabcp, name='bookstore-booksabcp'),
    path('Fantasyabcp', views.Fantasyabcp, name='Fantasyabcp'),
    path('Horrorabcp', views.Horrorabcp, name='Horrorabcp'),
    path('Nonfictionabcp', views.Nonfictionabcp, name='Nonfictionabcp'),
    path('Sciencefictionabcp', views.Sciencefictionabcp, name='Sciencefictionabcp'),
    path('Thrillerabcp', views.Thrillerabcp, name='Thrillerabcp'),
    path('Satireabcp', views.Satireabcp, name='Satireabcp'),
    path('Bestsellersabcp', views.Bestsellersabcp, name='Bestsellersabcp'),
    
    path('authors/<id>', views.authors, name='authors'),
]
