# Generated by Django 2.2.5 on 2019-09-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_user',
            old_name='author',
            new_name='user',
        ),
    ]
