# Generated by Django 2.2.5 on 2019-11-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20191018_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='aveRating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
