# Generated by Django 2.2.5 on 2019-11-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_book_averating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['price']},
        ),
    ]
