# Generated by Django 2.2.5 on 2019-10-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20191004_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='anonymity',
            field=models.CharField(choices=[('Username', 'Username'), ('Anonymous', 'Anonymous'), ('Full Name', 'Full Name')], default='Username', max_length=50),
        ),
    ]
