# Generated by Django 2.2.5 on 2019-10-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20191010_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='anonymity',
            new_name='anonymous',
        ),
    ]
