# Generated by Django 2.2.5 on 2019-10-27 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_auto_20191018_1922'),
        ('cart', '0003_auto_20191011_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveForLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('items', models.ManyToManyField(blank=True, to='bookstore.Book')),
            ],
        ),
    ]
